version: 2.1

jobs:
  build-aarch64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: uname -a

      - checkout
      - run:
          name: Build Classic
          command: |
            docker build . -t proxy:v1
            docker create --name ps proxy:v1
            mkdir -p build/docker
            docker cp ps:/usr/local/bin/proxy_server build/docker

      - store_artifacts:
          path: build/docker

  build:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
         name: Update OS
         command: |
          sudo apt-get update
          sudo apt-get install -y
          sudo rm -rf /var/lib/apt/lists/*

      - run:
          name: Install CMake&Ninja
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build

      - run:
          name: Check versions
          command: |
            g++ --version
            cmake --version

      - run:
          name: Build Classic
          command: |
            mkdir build
            cd build
            cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_BUILD_WERROR=OFF
            ninja -j1
            cp -r bin /tmp

      - store_artifacts:
          path: /tmp/bin

workflows:
  build-workflow:
    jobs:
      - build
      - build-aarch64
