version: 2.1

jobs:
  build-aarch64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run:
          name: Check OS
          command: uname -a

      - checkout
      - run:
          name: Build in docker
          command: |
            docker build . -t proxy:v1
            docker create --name ps proxy:v1
            mkdir -p build/docker
            docker cp ps:/usr/local/bin/proxy_server build/docker

      - store_artifacts:
          path: build/docker

  build-x86_64:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - run:
          name: Check OS
          command: uname -a

      - checkout
      - run:
          name: Build in docker
          command: |
            docker build . -t proxy:v1
            docker create --name ps proxy:v1
            mkdir -p build/docker
            docker cp ps:/usr/local/bin/proxy_server build/docker

      - store_artifacts:
          path: build/docker

workflows:
  build-workflow:
    jobs:
      - build-x86_64
      - build-aarch64
